components:
  schemas:
    productcheckout:
      type: object
      properties:
        user_id:  
          type: integer
          required:
            - user_id
        product_id:
          type: string
          required:
            - product_id
        product_bag_id:
          type: integer
          required:
            - product_bag_id
        product_checkout_id:  
          type: integer
          required:
            - product_checkout_id
        image:
          type: string
          required:
            - image
        product_name:
          type: string
          required:
            - product_name
        brand:
          type: string
          required:
            - brand
        price:
          type: integer
          required:
            - price
        total_price:
          type: integer
          required:
            - price
        total_cost:
          type: integer
          required:
            - price
        total_order:
          type: integer
          required:
            - total_price
post:
  responses: 
    '200':
      headers: 
        Content-Type:
          description: optional
          content:
            application/json:
              schema:
                type: string
        Authorization:
          description: put token to access all route
          content:
            access_token:
              schema:
                type: string
        Set-Cookie:
          description: Set other data like product id
          content:
            schema:
              example: PRC_ID=string; USR_ID=integer; PRC_B_ID=integer; CHE_ID=integer; Path=/product/checkout;
      description: Products in checkout
  requestBody:
    content:
      multipart/form-data:
        schema:
          $ref: '#/components/schemas/productcheckout'
get:
  responses: 
    '200':
      headers: 
        Content-Type:
          description: optional
          content:
            application/json:
              schema:
                type: string
        Authorization:
          description: put token to access all route
          content:
            access_token:
              schema:
                type: string
        Cookie:
          description: Set other data like product id
          content:
            schema:
              example: PRC_ID=string; USR_ID=integer; PRC_B_ID=integer; CHE_ID=integer; Path=/product/checkout;
      description: Products in checkout
      content:
        application/json:
          example:
            {
              "status": 200,
              "message": "Successfully get products in checkout",
              data: {
                product_bag_id: integer,
                product_checkout_id: integer,
                product_id: string,
                customer_id: integer,
                image: string,
                product_name: string,
                brand: string,
                quantity: integer,
                price: integer,
                total_price: integer,
                total_cost: integer,
                total_order: integer
              }
            }