POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
  "email": "maulanazn@mail.com",
  "password": "maulanazn123"
}

###

GET http://localhost:3000/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE4MDAwMDAwMDAwMDAsIklkIjoiMWFkMzE0MjktYWJiZi00NDFiLTk5MDUtNmMyYjViNzhmYzNiIn0.DGeTjLoXLznmlSoSlQO1Mqk6hGjJAB5D-6walgMJIxvVNJX5si3izhFhCaOkh3551i87B-x7GKPtsHxJqYffFg

###

GET http://localhost:3000/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE4MDAwMDAwMDAwMDAsIklkIjoiMWFkMzE0MjktYWJiZi00NDFiLTk5MDUtNmMyYjViNzhmYzNiIn0.DGeTjLoXLznmlSoSlQO1Mqk6hGjJAB5D-6walgMJIxvVNJX5si3izhFhCaOkh3551i87B-x7GKPtsHxJqYffFg

###

GET http://localhost:3000/product?id=65668ad0b0e856f8de4e32b9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE4MDAwMDAwMDAwMDAsIklkIjoiMWFkMzE0MjktYWJiZi00NDFiLTk5MDUtNmMyYjViNzhmYzNiIn0.DGeTjLoXLznmlSoSlQO1Mqk6hGjJAB5D-6walgMJIxvVNJX5si3izhFhCaOkh3551i87B-x7GKPtsHxJqYffFg
