@startuml @WhiteSmoke

entity account(
    acc_number VARCHAR UNIQUE NOT NULL PRIMARY KEY,
    acc_owner VARCHAR NOT NULL,
    acc_date_created DATE NOT NULL DEFAULT NOW(),
    acc_balance DECIMAL(10, 0) NOT NULL
);

entity transaction(
    trs_id BIGINT UNIQUE NOT NULL PRIMARY KEY,
    prd_order VARCHAR,
    trs_from_account VARCHAR NOT NULL,
    trs_date DATE NOT NULL DEFAULT NOW(),
    trs_amount DECIMAL(10, 0) NOT NULL,
    trs_type CHAR(2) NOT NULL,
    FOREIGN KEY(prd_order) REFERENCES products(id) ON UPDATE CASCADE ON DELETE CASCADE, 
    ' prd_order foreign key is not available for a while
    FOREIGN KEY(trs_from_account) REFERENCES account(acc_number) ON UPDATE CASCADE ON DELETE CASCADE
);

entity transaction_transfer(
    trs_id BIGINT NOT NULL PRIMARY KEY,
    trs_to_account VARCHAR NOT NULL,
    trs_status CHAR(1) NOT NULL,
    FOREIGN KEY(trs_id) REFERENCES transaction(trs_id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(trs_to_account) REFERENCES account(acc_number) ON UPDATE CASCADE ON DELETE CASCADE
);


@enduml