openapi: '3.0.2'
info:
  title: Pay book backend
  version: '1.0'
servers:
  - url: http://{devurl}/api
    description: Url list
    variables:
      devurl:
        enum:
          - localhost:3000
          - belanjabackend.cyclic.com
        default: localhost:3000
components:
  schemas:    
    product:
      type: object
      properties:
        category_name:
          type: object
          properties:
            shoes:
              type: string
            shirt:
              type: string
            hoodie:
              type: string
            sweater:
              type: string
            any:
              type: string
        image:
          type: string
        product_name:
          type: string
        brand:
          type: string
        rating:
          type: integer
        price:
          type: integer
        color:
          type: object
          properties:
            yellow:
              type: string
            black:
              type: string
            red:
              type: string
            green:
              type: string
            any:
              type: string
        size:
          type: string
        quantity:
          type: integer
paths:  
  /home:
    description: Home page / all products
    $ref: "paths/homepage.yaml"
  /register/customer:
    description: Login as customers
    $ref: "paths/authentication/register_customer.yaml"
  /register/seller:
    description: Login as seller
    $ref: "paths/authentication/register_seller.yaml"
  /customer/profile:
    description: Check customer profile
    $ref: "paths/profile/profile_customer.yaml"
  /customer/cart:
    description: Check customer cart
    $ref: "paths/cart/customer_cart.yaml"
  /address/customer:
    description: Customer address
    $ref: "paths/profile/shipping_address.yaml"
  /product/:store_name/:product_name:
    description: Detail product
    $ref: "paths/product/detail.yaml"
  /product/bag:
    description: Product bag
    $ref: "paths/product/product_bag.yaml"
  /product/checkout:
    description: Product checkout
    $ref: "paths/product/product_checkout.yaml"