@startuml WhiteSmoke

entity UserSeller {
    customer_id integer <<PK>>
    user_name string
    email string
    password string
    created_at timestamp
    updated_at timestamp
    deleted_at timestamp
}

entity UserCustomer {
    seller_id integer <<PK>>
    user_name string
    email string
    phone number
    store_name string
    password string
    created_at timestamp
    updated_at timestamp
    deleted_at timestamp
}

entity Address {
    address_id integer <<PK>>
    customer_id integer <<FK>>
    address_type enum('home', 'office')
    recipient_name string
    recipient_phone number
    address string
    postal_code string
    city string
}

entity Product {
    product_id string <<PK>>
    seller_id integer <<FK>>
    category_name enum(category)
    shoes string
    shirt string
    hoodie string
    sweater string
    any string
    image string
    product_name string
    brand string
    rating integer
    price integer
    color enum(color)
    size string
    quantity integer
}

@enduml